


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nggit-dep
spec:
  selector:
    matchLabels:
      app: nggit
  replicas: 3 
  template:
    metadata:
      labels:
        app: nggit
    spec:
      containers:
      - name: nggit
        image: nginx
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nggit-svc
  labels:
    app: nggit
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nggit
  type: NodePort
