apiVersion: v1
kind: Service
metadata:
  name: {{ include "charto.fullname" . }}
  labels:
    environment: {{ .Values.environment }}
    demo: "{{ .Values.demo }}"
    {{- include "charto.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "charto.selectorLabels" . | nindent 4 }}
